### ISSUE TITLE
Issue with android version 14 one plus 11 R

### ISSUE THREAD

**Issue by gadgetsteach** [tim06/VPNProtocols#6]
FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: altkeys.ai.vpn:openvpn, PID: 31278
                                                                                                    java.lang.RuntimeException: Unable to bind to service com.tim.openvpn.service.OpenVPNService@867a627 with Intent { cmp=altkeys.ai.vpn/com.tim.openvpn.service.OpenVPNService (has extras) mCallingUid=10205 }: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{feb65b7 31278:altkeys.ai.vpn:openvpn/u0a205} targetSDK=34
                                                                                                    	at android.app.ActivityThread.handleBindService(ActivityThread.java:4985)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindService(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2464)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:257)
                                                                                                    	at android.os.Looper.loop(Looper.java:368)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8848)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
                                                                                                    Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{feb65b7 31278:altkeys.ai.vpn:openvpn/u0a205} targetSDK=34
                                                                                                    	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
                                                                                                    	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
                                                                                                    	at android.os.Parcel.readParcelableInternal(Parcel.java:4900)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:4882)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3082)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3071)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3054)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2996)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
                                                                                                    	at android.app.Service.startForeground(Service.java:775)
                                                                                                    	at com.tim.notification.NotificationHelper.startNotification(NotificationHelper.kt:15)
                                                                                                    	at com.tim.openvpn.service.OpenVPNService.onBind(OpenVPNService.kt:94)
                                                                                                    	at android.app.ActivityThread.handleBindService(ActivityThread.java:4970)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindService(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2464) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:257) 
                                                                                                    	at android.os.Looper.loop(Looper.java:368) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8848) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by gadgetsteach** [comment]
Any ways to fixing

**Comment by tim06** [comment]
Hello! Due to the updated foreground-service operation in Android, there are new rules for registering in the manifest. You can use the new version 1.1.0
